apiVersion: v1
kind: ImageStream
metadata:
  name: rhel7
  namespace: REPLACE_WITH_NAMESPACE
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: REPLACE_WITH_DOCKER_REPOSITORY/rhel7/rhel:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
